version: "3"

services:
  myhwrabbit:
    image: rabbitmq:3-management
    container_name: rabbithw
    hostname: rabbithw
    ports:
      - "5672:5672"
      - "15672:15672"
  rabbitproducerhw:
    build: ./producer
    depends_on:
      - myhwrabbit
    container_name: rabbithwproducer
    command: tail -f /dev/null
    volumes:
      - .:/code
  rabbitconsumerhw:
    build: ./consumer
    depends_on:
      - myhwrabbit
    container_name: rabbithwconsumer
    command: tail -f /dev/null
    volumes:
      - .:/code
