node {
    def app

    stage('Initialize'){
           def dockerHome = tool 'myDocker'
           env.PATH = "${dockerHome}/bin:${env.PATH}"
       }

    stage('Clone repository') {
        /* Clone our repository */

        checkout scm
    }

    stage('Build image') {
      dir('PythonWithDocker') {
        /* Build the docker image */
        withEnv(['HOME='+pwd()]){
          app = docker.build("bolbeck/simplepythonimage")
        }
      }
    }


}
