node {
    def app


    stage('Clone repository') {
        /* Clone our repository */

        checkout scm
    }

    stage('Build image') {
      dir('PythonWithDocker') {
        /* Build the docker image */
      docker.withTool('myDocker') {
        app = docker.build("bolbeck/simplepythonimage")
        }
      }
    }

    stage('Test image') {
        /* Test image ... */

      docker.withTool('myDocker') {
        app.inside {
            sh 'echo "Tests passed"'
        }
      }
    }

    stage('Push image') {
        /* Push images: First is tagged with the build BUILD_NUMBER
         the second is just tagged latest !*/
      docker.withTool('myDocker') {
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
            app.push("${env.BUILD_NUMBER}")
            app.push("latest")
          }
        }
    }

   stage('Deploy') {
     /* Deploy image to Kubernetes */
     kubernetesDeploy configs: "PythonWithDocker/Kubernetes/appManifests/*.yaml", kubeconfigId: 'main__kubeconfig'
   }
}
