node {
    def app

    stage('Clone repository') {
        /* Clone our repository */

        checkout scm
    }

    stage('Build image') {
      dir('PythonWithDocker') {
        /* Build the docker image */

        app = docker.build("bolbeck/simplepythonimage")
      }
    }

    stage('Test image') {
        /* Test image ... */

        app.inside {
            sh 'echo "Tests passed"'
        }
    }

    stage('Push image') {
        /* Push images: First is tagged with the build BUILD_NUMBER
         the second is just tagged latest */
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
            app.push("${env.BUILD_NUMBER}")
            app.push("latest")
        }
    }

    stage('Push to Minikube') {
      /* Push image to Minikube */
      dir('PythonWithDocker/Kubernetes') {
        sh("kubctl apply -f deployment.yaml -f service.yaml")
      }
    }
}
